### ISSUE TITLE
Temper (PC Engine emulator): button remapping issues

### ISSUE THREAD

**Issue by c0d3h4x0r** [retrogamehandheld/RG-350#1]
Note: If this is not the right place to report bugs against the Temper emulator for the RG350, please redirect me to the appropriate issue tracker to use instead.  I've been unable to find any clear information about where/how to file bug reports with the emulators or system software on my RG350, so this seems like the most obvious place to file an issue.

1. The L2/R2 buttons cannot be mapped to any of the in-game buttons.
2. The L/R thumbstick buttons cannot be mapped to any of the in-game buttons.
3. Remapping the SELECT button doesn't work (SELECT button always brings up the menu, no matter what in-game button you map it to).
4. Remapping the X button actually remaps the Y button.
5. Remapping the Y button actually remaps the X button.

**Comment by npaladin2000** [comment]
Please report this to the author/maintainer of the Temper software

**Comment by c0d3h4x0r** [comment]
> Please report this to the author/maintainer of the Temper software

How?  Where?

**Comment by npaladin2000** [comment]
Unfortunately, I don't know. I haven't been able to track down the owner of the software yet. You can ask around on the Discord, see if anyone else knows. But so far no one has stepped up to own this issue, so the software may also be abandoned.
