### ISSUE TITLE
General: No universal consistent way to exit applications/emulators and return to GMenu2x

### ISSUE THREAD

**Issue by c0d3h4x0r** [retrogamehandheld/RG-350#10]
For some apps, the SELECT button exits back to the main menu.
For other apps, the START button exits back to the main menu.
For other apps, you have to invoke some kind of in-app menu and choose "Exit" or "Quit".
For other apps, there's just no way to exit them at all, and the user has to hit the RESET button along the bottom edge of the device.

This is a mess.  There should be a single, consistent, universal way to always quit any application and get back to the menu without having to reboot/reset the system and risk filesystem corruption.

**Comment by fgl82** [comment]
@c0d3h4x0r which applications need you to reset? Worse cases scenario, there's a shortcut, power+select, that kills the current app, no need to reset

**Comment by npaladin2000** [comment]
@c0d3h4x0r this is not an OS issue or a device issue, it's up to the author of each emulator to define the menu button combination for their software.

**Comment by c0d3h4x0r** [comment]
The fact that it's up to the author of each emulator is the fundamental design flaw in the system software.  This should not have been closed.

**Comment by c0d3h4x0r** [comment]
How would an ordinary user have known that POWER+SELECT kills the current app?  Where is that documented, other than here?

**Comment by npaladin2000** [comment]
Again, you're mixing OS and applications. Power+SELECT is an OS function...like kill -9 or like the X button at the top right of a window. But what they put in the window is up to the application developer, they can set whatever keystroke combo they want to be their "Menu" command and the OS developers can only suggest otherwise, not enforce. The issue remains closed as a non-issue.

**Comment by c0d3h4x0r** [comment]
I'm not mixing or confusing anything.  I'm saying that the system UI should provide an option the user can configure to kill (quit) any app.  It sounds like POWER+SELECT already exists, it just isn't at all discoverable (or configurable, apparently).
