### ISSUE TITLE
Strange screen flickering (upside-down) on RG-350

### ISSUE THREAD

**Issue by gabuzom** [retrogamehandheld/RG-350#12]
Hello,

I am asking here because i find no documentation of similar case, nor any other place to ask.

Upon booting up, with the Anbernic logo, the screen of my RG-350 flickers a few times in a strange way: the image appears upside-down!

The same happens within Dingux Commander, during file operations...

I considered that as minor until i realized it also happen when using the PSX emulator!! Now it starts to be really annoying...

I thought of maybe a software issue, so i tried alternatively the latest Rogue OS/firmware, as well as a 1.5 and 1.5.1 "stable". All versions had the same symptom.

Can anyone help me? Has this happened to anyone before? Where should I look? How to diagnose? Is that software or hardware you think?

Thanks!

**Comment by GreenMan36** [comment]
A clean install should fix all software related issues, you should do that with the stock firmware to verify it is working and then re-flash to see if the issue is resolved or persists on the firmware.

**Comment by gabuzom** [comment]
Thanks for your reply. I tried clean installs of all available firmware and the problem persists. therefore i believe it is a hardware problem that came shipped with my RG-350.

what i identified so far:
* it only appears when *reading* data
* it only appears when reading from the *external* SDcard, whatever the SDcard (tested with 5 different sizes/models/manufacturers...)

I realize it's way beyond the scope of this project here... but if anyone has ever seen such a problem (and has a vague idea of a fix) I am curious to hear about it... with not much hope though :)

**Comment by GreenMan36** [comment]
Hmm you might have some luck by asking about it in de Discord in the RG-350 related channels.
Most device owners are active in the Discord.
I hope they'll be able to help you further.

The link to the Discord is at the bottom of our site.
