### ISSUE TITLE
Persona Freezes

### ISSUE THREAD

**Issue by joae1234** [retrogamehandheld/RG-350#14]
On the ps1 emulator the game freezes when checking for memory cards

**Comment by GreenMan36** [comment]
Could you provide more information? What firmware are you using? Is it the latest? What emulator are you using? What Memory card, etc.

**Comment by joae1234** [comment]
I am not sure about firmware but,it's a anbernic it says the Kernel version is: 3.12.0-dingux+, I only saw the memory cards being mcd001.mcr and mcd002.mcr but there where no settings about that,, and the emulator is Pcsx4all-RG350 2.4

**Comment by GreenMan36** [comment]
Please update to the latest firmware version before posting an issue.
Please update and if the issue persists, comment again.
Also try to use a different memory card than the one your device got shipped with. They can be a point of failure.

I'll close the issue after a week of inactivity.
