### ISSUE TITLE
Issue after update

### ISSUE THREAD

**Issue by MaxCarnage2012** [retrogamehandheld/RG-350#16]
I just got the RG 350M device and was provided this link to update to the latest firmware RG-350 Update (1.5.1) 10-27-2019-2 (STABLE RELEASE)
I followed the instructions and now after it restarted i am stuck on a black screen.

**Comment by GreenMan36** [comment]
Are you sure you followed the link on [RGhandhelds](https://www.rghandhelds.com/) as it links to the [RG350m](https://github.com/retrogamehandheld/rg350m/wiki) specific GitHub, which isn't the same as you are on right now.

Current newest firmware is stock, no one has made a custom firmware we're willing to share as recommended yet.
