### ISSUE TITLE
Firmware update link is down

### ISSUE THREAD

**Issue by jserodio** [retrogamehandheld/RG-350#17]
https://rg350.i0.wtf/RG350-HDMI-20-05-10.IMG

This link is not working for me guys.
I get the error: 502 Bad Gateway

**Comment by cmandlbaur** [comment]
Same for me :/

**Comment by jserodio** [comment]
I just downloaded it from this website
https://droidbox.co.uk/how-to/how-to-update-rg350-and-rg350m-firmware-with-opk/

However, this firmware is for the BETA, and the updated wiki on this github repository says that the firmware link is the STABLE version, which we are unable to access.

**Comment by GreenMan36** [comment]
Ill tell @npaladin2000 he made the latest change to the page so he should know more.

**Comment by GreenMan36** [comment]
Hi (if I recall correctly) there was an issue with the firmware's binary so the link has been reverted for now.

Whoops 😅

**Comment by GreenMan36** [comment]
I'm not sure when the given HDMI firmware will be rereleased, I'll close the issue now.
