### ISSUE TITLE
Temper (PC Engine emulator): file selector should not list .cue files for CD-ROM games

### ISSUE THREAD

**Issue by c0d3h4x0r** [retrogamehandheld/RG-350#4]
The file selector that appears when first launching the emulator should not list .cue files as possibly choices, since Temper is unable to load them.  The file selector should only list the .bin files, since those are the only ones Temper can directly load.

**Comment by npaladin2000** [comment]
Please report this to the author/maintainer of the Temper software

**Comment by c0d3h4x0r** [comment]
> Please report this to the author/maintainer of the Temper software

Where?  How?

**Comment by npaladin2000** [comment]
Unfortunately, I don't know. I haven't been able to track down the owner of the software yet. You can ask around on the Discord, see if anyone else knows. But so far no one has stepped up to own this issue, so the software may also be abandoned.
