### ISSUE TITLE
Temper (PC Engine emulator): rapid-fire doesn't work

### ISSUE THREAD

**Issue by c0d3h4x0r** [retrogamehandheld/RG-350#5]
In the "Reconfigure Pad" menu, no matter which physical buttons I map to "Rapid I" or "Rapid II", they do not work.  It looks like the rapid fire feature is completely broken, which makes some games (such as Bonk's Adventure) that depend on it largely unplayable.

**Comment by npaladin2000** [comment]
Please report this to the author/maintainer of the Temper software

**Comment by c0d3h4x0r** [comment]
> Please report this to the author/maintainer of the Temper software

Where?  How?

**Comment by npaladin2000** [comment]
Unfortunately, I don't know. I haven't been able to track down the owner of the software yet. You can ask around on the Discord, see if anyone else knows. But so far no one has stepped up to own this issue, so the software may also be abandoned.
