### ISSUE TITLE
Temper (PC Engine emulator): no way to get correct aspect ratio

### ISSUE THREAD

**Issue by c0d3h4x0r** [retrogamehandheld/RG-350#6]
Under "Change options", there are only two possible choices for "Scale screen width":

- no: then the aspect ratio is too narrow
- yes: then the aspect ratio is too wide

There really needs to be an additional setting there, maybe called "original" or "aspect", that will scale the width correctly to produce the right physical aspect ratio so that the image is neither squished nor stretched.

**Comment by npaladin2000** [comment]
Please report this to the author/maintainer of the Temper software

**Comment by c0d3h4x0r** [comment]
> Please report this to the author/maintainer of the Temper software

Where?  How?

**Comment by npaladin2000** [comment]
Unfortunately, I don't know. I haven't been able to track down the owner of the software yet. You can ask around on the Discord, see if anyone else knows. But so far no one has stepped up to own this issue, so the software may also be abandoned.
