### ISSUE TITLE
UAE4ALL (Amiga emulator): no support for hard drive files (.HDF files)

### ISSUE THREAD

**Issue by c0d3h4x0r** [retrogamehandheld/RG-350#8]
UAE4ALL is completely lacking any support for HDF files, as far as I can tell.  I can find no way to tell it to load mine.  That makes my entire WHDLoad-ed game collection entirely unplayable/unusable on the RG350.

This is a HUGE disappointment, because the main reason I bought the RG350 was to try to get out of the stuck situation I was in with my GPD XD in regards to Amiga emulation: none of the Amiga emulators available for the GPD XD have a completely working set of features, and none of them have been updated in ages (presumably due to the Android OS not being open-source and requiring developers to publish their apps to the Google Play store).  I was really hoping and expecting the RG350 to have a better story for Amiga emulation, since it was advertised as being so "open source" compared to the Android-based handhelds.

**Comment by npaladin2000** [comment]
Please report this to the author/maintainer of the UAE4ALL software.

**Comment by c0d3h4x0r** [comment]
> Please report this to the author/maintainer of the UAE4ALL software.

Where?  How?

**Comment by npaladin2000** [comment]
UAE4ALL is maintained here: https://github.com/zear/uae4all

**Comment by c0d3h4x0r** [comment]
The 

> UAE4ALL is maintained here: https://github.com/zear/uae4all

The last update to that repository was 5+ years ago.  I would hardly call that "maintained".

**Comment by npaladin2000** [comment]
You'll have to take that up with him. He's the one who wrote it.
