### ISSUE TITLE
XMAME v1.3: No way to tell it where to look for ROMs

### ISSUE THREAD

**Issue by c0d3h4x0r** [retrogamehandheld/RG-350#9]
My ROMs are in a folder on my external microSD card.  I can't seem to find any way to tell the emulator to look in that location for the ROMs, so of course it thinks there are zero games available.  I don't want to copy the ROMs onto the internal microSD card, because it's not nearly large enough to hold them all.

**Comment by c0d3h4x0r** [comment]
As a workaround, I used the USB-to-PC connection to SSH into OpenDingux, and I removed the following folders...

/media/data/local/share/xmame/xmame52/roms
/media/data/local/share/xmame/xmame69/roms
/media/data/local/share/xmame/xmame84/roms

...and replaced them with symlinks to /media/RG350-Games/roms/MAME/Roms.  But most users aren't going to know to go do this -- they're going to expect the emulator's frontend/UI to provide an option to point it at the correct folder on the external microSD card where it can find the ROMs.  (Note that Mame4All does provide such an option.)

**Comment by npaladin2000** [comment]
Please report this to the author/maintainer of the XMAME software

**Comment by c0d3h4x0r** [comment]
> Please report this to the author/maintainer of the XMAME software

Where?  How?

**Comment by npaladin2000** [comment]
Looks like Slaanesh was originally maintaining it but that was back in 2014. I'd ask in the DIscord to see who's working with it now.
